line-length = 79
fix = true


[lint]
extend-select = ["E501"]
select = [
    "I001",  # Enforces imports being correctly ordered
    "I002",  # Ensures imports are correctly grouped,
    "F401",  # Unused imports
    "F841",  # Unused variables
]